spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/doctor_dashboard
    username: root
    password: Pranay@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect