


spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/doctor_dashboard
    username: 
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - profile
              - email

