


spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/doctor_dashboard
    username: root
    password: Pranay@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  66297814659-gkj68lfu116ai19tb6e2rfacqt9bja0s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

